### ISSUE TITLE
ERROR_SUCCESS conflict with a macro from <windows.h>

### ISSUE THREAD

**Issue by wojdyr** [chadaustin/sajson#40]
Just to let you know: when including sajson.h after <windows.h> I get one error:
ERROR_SUCCESS is defined as a macro (0x0) in Windows headers.

**Comment by iboB** [comment]
Perhaps changing it to ERROR_NO_ERROR (or simply NO_ERROR) is the way to do it. This will break backwards compatibility slightly but I guess very few users actually check for the ERROR_SUCCESS constant.

**Comment by ddevienne** [comment]
Also ran into that one. Unfortunate choice of name.
