### ISSUE TITLE
Stream json parsing

### ISSUE THREAD

**Issue by vmalyasov** [chadaustin/sajson#44]
Is there a way to parse the JSON string from a network stream (JSON as bytes stream or data chunks)?

**Comment by chadaustin** [comment]
There isn't, no.  sajson relies on having the entire input document available.  (Fortunately, sajson parses at a rate of hundreds of MB per second, so streaming should not be necessary except in the most extreme cases.)

**Comment by chadaustin** [comment]
Ah, yeah.  If keeping the entire JSON document in memory is not desirable, sajson is not a good fit.  :/  I would look for a streaming parser.

Cheers!
