### ISSUE TITLE
'parse_flags' redefinition ; different storage class

### ISSUE THREAD

**Issue by mikelaltadi** [chadaustin/sajson#48]
Hello Im trying to compile with visual studio 2015 and this error appears:
'parse_flags' redefinition ; different storage class

This is located in sajson.h line 152  constexpr uint8_t globals_struct<unused>::parse_flags[256] = {

Any idea?

**Comment by chadaustin** [comment]
Hi @mikelaltadi. I'm not sure. Can you paste the entire error?

**Comment by wojdyr** [comment]
After this change I get linking errors with GCC 9 and 10 (I haven't checked other versions). I'm testing it on Ubuntu 20.04.

```
wojdyr@tc:~/fresh/sajson/example$ g++-9 -g -I ../include main.cpp 
/usr/bin/ld: /tmp/ccdOLULc.o: in function `sajson::internal::is_plain_string_character(char)':
/home/wojdyr/fresh/sajson/example/../include/sajson.h:170: undefined reference to `sajson::internal::globals_struct<void>::parse_flags'
/usr/bin/ld: /tmp/ccdOLULc.o: in function `sajson::internal::is_whitespace(char)':
/home/wojdyr/fresh/sajson/example/../include/sajson.h:175: undefined reference to `sajson::internal::globals_struct<void>::parse_flags'
collect2: error: ld returned 1 exit status
```
