### ISSUE TITLE
Documentation with API references

### ISSUE THREAD

**Issue by erez-o** [chadaustin/sajson#49]
Hi, 

I've created a documentation with API references - https://sajson.docsforge.com/

The docs are updated automatically so it will be in sync if the source files, readme, or examples are changed. 

If you want me to add or remove any pages (like namespace internal), please let me know :)

Disclaimer, I'm the creator of docsforge.

**Comment by chadaustin** [comment]
Hi @erez-o. Cool! Feel free to make a PR to link to it.

**Comment by erez-o** [comment]
Thanks.

Opened PR #50

**Comment by chadaustin** [comment]
Thanks!
